const DB_ERROR_CODES = { DUPLICATE: 11000 };
const DB_UPDATE_STATUS = { UPDATED: 1, REJECTED: 0 };
const DB_DELETE_STATUS = { DELETED: 1, REJECTED: 0 };

module.exports = {
  DB_ERROR_CODES,
  DB_UPDATE_STATUS,
  DB_DELETE_STATUS,
};
